### ISSUE TITLE
Issue during conversion to Unicode

### ISSUE THREAD

**Issue by NicoFeliceEUROTECH** [eppesuig/baan-UTF-T-decoder#1]
Hi,

I found there is an issue when you try to convert the code to unicode.
This part of code should be unsigned long c = ((b3 & 127) | ((b2 & 127)<<7) | ((b1 & 127)<<14)) - 0x0F0000UL; (so is needed to change the last b3 with b1).

Thanks and regards,
Nico

**Comment by eppesuig** [comment]
Thank you very much. I am going to fix the code.

Giuseppe

**Comment by NicoFeliceEUROTECH** [comment]
Thanks you to for the contribution of this code.
You saved "my life".

Ciao,
Nico

**Comment by eppesuig** [comment]
closed with commit 810f363
